stages:
  - build-using-runner
  - pull-image-to-server
  - run-on-server

 
build docker:
  stage: build-using-runner
  image: docker
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - "docker build -t iansinambela/frontend:1.0 ."
    - "docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN"
    - "docker push iansinambela/frontend:1.0"
      

pull image:
  stage: pull-image-to-server
  image: docker
  services:
    - docker:dind
  before_script:
    - "which ssh-agent || ( apt-get install openssh-client )"
    - mkdir -p ~/.ssh
    - touch ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - ssh-add id_rsa 
  script:
    - ssh -o StrictHostKeyChecking=no $VAR_USER@$VAR_IP -p $VAR_PORT "docker login -u $REGISTRY_USER -p $REGISTRY_TOKEN && docker pull iansinambela/frontend:1.0"

run image:
  stage: run-on-server
  image: docker
  services:
    - docker:dind
  before_script:
    - "which ssh-agent || ( apt-get install openssh-client )"
    - mkdir -p ~/.ssh
    - touch ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - ssh-add id_rsa 
  script:
    - ssh -o StrictHostKeyChecking=no $VAR_USER@$VAR_IP -p $VAR_PORT "docker run -d iansinambela/frontend:1.0"
 

